### ISSUE TITLE
hashcode implementation

### ISSUE THREAD

**Issue by moreaki** [octaviospain/Musicott#1]
Reading through your code online, I wonder if the hashcode() implementation in https://github.com/octaviospain/Musicott/blob/master/src/com/musicott/model/MusicLibrary.java#L51 should include the multiplication of the initial hash value to avoid future surprises when adding more fields. Suggestion:

hash = 73 * hash + tracks.hashCode();

**Comment by octaviospain** [comment]
You're right, thank you for the advise. This fix will be committed with the next release (0.7) coming soon.
