### ISSUE TITLE
Missing artifact be.tarsos:transcoder:jar:1.2 , can't be download from Maven

### ISSUE THREAD

**Issue by goxr3plus** [octaviospain/Musicott#11]
Today downloaded the project and tried to run but can't get : 

![screenshot_6](https://user-images.githubusercontent.com/20374208/43975425-46a31818-9ce6-11e8-80c7-0a67db345d27.jpg)

``` JAVA
<dependency>
	<groupId>be.tarsos</groupId>
	<artifactId>transcoder</artifactId>
	<version>1.2</version>
</dependency>
```

I have tried all the ways but can't get it working . 

Also trying Maven Install produces -> 

![screenshot_5](https://user-images.githubusercontent.com/20374208/43975433-497584e0-9ce6-11e8-9197-7fa80b8d5042.jpg)

**Comment by octaviospain** [comment]
The library `jar` is inside the `lib` folder. Have you run this from the root folder?

```
mvn install:install-file -Dfile=lib/TarsosTranscoder-1.2.jar -DgroupId=be.tarsos -DartifactId=transcoder -Dversion=1.2 -Dpackaging=jar
```

**Comment by goxr3plus** [comment]
Octavio isn't there any way to get it somewhere online with Maven ? Only locally ?

**Comment by goxr3plus** [comment]
@octaviospain  O my god ,thank you i missed : 

``` JAVA
mvn install:install-file -Dfile=lib/TarsosTranscoder-1.2.jar -DgroupId=be.tarsos -DartifactId=transcoder -Dversion=1.2 -Dpackaging=jar
mvn install:install-file -Dfile=lib/iTunesUtilities.jar -DgroupId=com.worldsworstsoftware -DartifactId=itunesutilities -Dversion=1.2 -Dpackaging=jar
mvn install:install-file -Dfile=lib/jaudiotagger-2.2.6-SNAPSHOT.jar -DgroupId=net.jthink -DartifactId=jaudiotagger -Dversion=2.2.6-SNAPSHOT -Dpackaging=jar
```

Octavio i am trying to undestand how you create the sound spectrum wave from sound files , can you provide some help on it :)

**Comment by octaviospain** [comment]
The libraries that are not available from a maven public repository are in the lib folder

https://github.com/octaviospain/Musicott/tree/master/lib

Please follow the steps mentioned in the project home:

 1. Clone Musicott at any directory `git clone https://github.com/octaviospain/Musicott.git`
 2. Build with maven at Musicott's root folder (where `pom.xml` is located)  with `mvn install -Dmaven.test.skip=true`
 3. Install this two required jar libraries into the local maven repository executing
 ```
 mvn install:install-file -Dfile=lib/TarsosTranscoder-1.2.jar -DgroupId=be.tarsos -DartifactId=transcoder -Dversion=1.2 -Dpackaging=jar
 mvn install:install-file -Dfile=lib/iTunesUtilities.jar -DgroupId=com.worldsworstsoftware -DartifactId=itunesutilities -Dversion=1.2 -Dpackaging=jar
 mvn install:install-file -Dfile=lib/jaudiotagger-2.2.6-SNAPSHOT.jar -DgroupId=net.jthink -DartifactId=jaudiotagger -Dversion=2.2.6-SNAPSHOT -Dpackaging=jar
 ```
 4. Run with `mvn exec:java -Dexec.mainClass=com.transgressoft.musicott.MusicottApplication`

**Comment by goxr3plus** [comment]
Just managed to run it , something final : 

@octaviospain  i am trying to understand how you create the sound spectrum wave from sound files , can you provide some help on it :)

**Comment by goxr3plus** [comment]
![screenshot_8](https://user-images.githubusercontent.com/20374208/43977209-06fe3430-9cec-11e8-82b5-77d6d8207fd9.jpg)

You are using Tarsos Transcoder but it's hard to find how classes connect  to create that .

**Comment by octaviospain** [comment]
Check the code inside [WaveformTask](
https://github.com/octaviospain/Musicott/blob/master/application/src/com/transgressoft/musicott/tasks/WaveformTask.java) and [WaveformPane](
https://github.com/octaviospain/Musicott/blob/master/application/src/com/transgressoft/musicott/view/custom/WaveformPane.java) classes.

Closing this.

**Comment by goxr3plus** [comment]
[I will start maintaining Tarsos Transcoder](https://github.com/goxr3plus/TarsosTranscoder) , publish on Maven and combine the code with newer [Jave2](https://github.com/a-schild/jave2)

In case you are interested that would be excellent :)

**Comment by octaviospain** [comment]
That is a good idea since that library is not under development anymore. A good point to start would be to discuss what is achievable and how, and then start some development. We can do this in some issue/ticket that you can open in your repo or the source one.
I though about replacing the Tarsos Transcoder with Jave2 library, maybe thats enough rather than combining them, I don't have enough info about them yet.

**Comment by goxr3plus** [comment]
Octavio i managed to remove Tarsos transcoder and use only Jave2 for Wave Spectrum Creation , i made also this have a look : 

![screenshot_2](https://user-images.githubusercontent.com/20374208/44040905-1444661a-9f25-11e8-9058-3b1af311d97d.jpg)

Published complete tutorial about it all the code here : 

https://github.com/goxr3plus/Java-Audio-Wave-Spectrum-API

Published also all the spectrum tutorials i have done till now : 

https://github.com/goxr3plus/Java-JavaFX-Audio-Tutorials-by-GOXR3PLUS

I added the new wave spectrum on the latest version of XR3Player :+1: 

https://github.com/goxr3plus/XR3Player

Happy coding :)

**Comment by octaviospain** [comment]
There is no tutorial in those links, just a screenshot; and the repo with the sample code containing a lot of commented lines copy pasted from my code.

You could have had bothered into removing the copyright header from your [WaveFormPane](https://github.com/goxr3plus/Java-Audio-Wave-Spectrum-API/blob/master/src/application/WaveFormPane.java) class :)

Happy quality coding :)
