### ISSUE TITLE
Error while building the project

### ISSUE THREAD

**Issue by piusalfred** [octaviospain/Musicott#13]
I get the below stacktrace 
`---
[ERROR] Failed to execute goal on project musicott: Could not resolve dependencies for project com.transgressoft.musicott:musicott:pom:0.10.1-b: Could not find artifact org.fxmisc.easybind:easybind:jar:1.0.4-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
`

My environment  specifications 
`Apache Maven 3.5.2
Maven home: /usr/share/maven
Java version: 1.8.0_171, vendor: Oracle Corporation
Java home: /usr/lib/jvm/jdk1.8.0_171/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-36-generic", arch: "amd64", family: "unix"
`

**Comment by octaviospain** [comment]
Did you modify the version of the `easybind` library in the `pom.xml` file? 
The version used is `1.0.3`, not `1.0.4-SNAPSHOT` which is not published in maven central. That's why the maven command is failing
Check the `pom.xml` file and verify that the version is the correct one:

```xml
        <dependency>
            <groupId>org.fxmisc.easybind</groupId>
            <artifactId>easybind</artifactId>
            <version>1.0.3</version>
            <scope>compile</scope>
        </dependency>
```

**Comment by piusalfred** [comment]
The version of the `easybind` in the `pom.xml` file was `1.0.4-SNAPSHOT` changed it to `1.0.3` and then i did run the command `mvn install -Dmaven.test.skip=true`
and the output is
<pre>[<font color="#FFFFFF"><b>INFO</b></font>] Scanning for projects...
[<font color="#FFFFFF"><b>INFO</b></font>] <b>------------------------------------------------------------------------</b>
[<font color="#FFFFFF"><b>INFO</b></font>] <b>Reactor Build Order:</b>
[<font color="#FFFFFF"><b>INFO</b></font>] 
[<font color="#FFFFFF"><b>INFO</b></font>] Musicott
[<font color="#FFFFFF"><b>INFO</b></font>] common
[<font color="#FFFFFF"><b>INFO</b></font>] preloader
[<font color="#FFFFFF"><b>INFO</b></font>] application
[<font color="#FFFFFF"><b>INFO</b></font>] 
[<font color="#FFFFFF"><b>INFO</b></font>] <b>------------------------------------------------------------------------</b>
[<font color="#FFFFFF"><b>INFO</b></font>] <b>Building Musicott 0.10.1-b</b>
[<font color="#FFFFFF"><b>INFO</b></font>] <b>------------------------------------------------------------------------</b>
Downloading from central: https://repo.maven.apache.org/maven2/org/fxmisc/easybind/easybind/1.0.3/easybind-1.0.3.pom
[<font color="#FFFFFF"><b>INFO</b></font>] <b>------------------------------------------------------------------------</b>
[<font color="#FFFFFF"><b>INFO</b></font>] <b>Reactor Summary:</b>
[<font color="#FFFFFF"><b>INFO</b></font>] 
[<font color="#FFFFFF"><b>INFO</b></font>] Musicott ........................................... <font color="#FFBA2A"><b>FAILURE</b></font> [ 21.185 s]
[<font color="#FFFFFF"><b>INFO</b></font>] common ............................................. <font color="#F99090"><b>SKIPPED</b></font>
[<font color="#FFFFFF"><b>INFO</b></font>] preloader .......................................... <font color="#F99090"><b>SKIPPED</b></font>
[<font color="#FFFFFF"><b>INFO</b></font>] application ........................................ <font color="#F99090"><b>SKIPPED</b></font>
[<font color="#FFFFFF"><b>INFO</b></font>] <b>------------------------------------------------------------------------</b>
[<font color="#FFFFFF"><b>INFO</b></font>] <font color="#FFBA2A"><b>BUILD FAILURE</b></font>
[<font color="#FFFFFF"><b>INFO</b></font>] <b>------------------------------------------------------------------------</b>
[<font color="#FFFFFF"><b>INFO</b></font>] Total time: 21.493 s
[<font color="#FFFFFF"><b>INFO</b></font>] Finished at: 2018-10-10T11:27:46+03:00
[<font color="#FFFFFF"><b>INFO</b></font>] Final Memory: 10M/135M
[<font color="#FFFFFF"><b>INFO</b></font>] <b>------------------------------------------------------------------------</b>
[<font color="#FFBA2A"><b>ERROR</b></font>] Failed to execute goal on project <font color="#09FAFA">musicott</font>: <font color="#FFBA2A"><b>Could not resolve dependencies for project com.transgressoft.musicott:musicott:pom:0.10.1-b: Failed to collect dependencies at org.fxmisc.easybind:easybind:jar:1.0.3</b></font>: Failed to read artifact descriptor for org.fxmisc.easybind:easybind:jar:1.0.3: Could not transfer artifact org.fxmisc.easybind:easybind:pom:1.0.3 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: Name or service not known: Unknown host repo.maven.apache.org: Name or service not known -&gt; <b>[Help 1]</b>
[<font color="#FFBA2A"><b>ERROR</b></font>] 
[<font color="#FFBA2A"><b>ERROR</b></font>] To see the full stack trace of the errors, re-run Maven with the <b>-e</b> switch.
[<font color="#FFBA2A"><b>ERROR</b></font>] Re-run Maven using the <b>-X</b> switch to enable full debug logging.
[<font color="#FFBA2A"><b>ERROR</b></font>] 
[<font color="#FFBA2A"><b>ERROR</b></font>] For more information about the errors and possible solutions, please read the following articles:
[<font color="#FFBA2A"><b>ERROR</b></font>] <b>[Help 1]</b> http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
</pre>

**Comment by octaviospain** [comment]
This error is caused by some DNS, proxy, or network connection on your side. 
Do you have set a proxy configuration on your computer?
[This link might help](https://stackoverflow.com/questions/19323678/error-in-resolving-buildtime-dependencies-while-installing-cloudstack-on-ubuntu)

**Comment by piusalfred** [comment]
It was caused by some network problem.Thanks, It worked.
