### ISSUE TITLE
It doesn't import mp3 files.

### ISSUE THREAD

**Issue by olgierd-on-fire** [octaviospain/Musicott#3]
I installed recent version and build with maven on OS X El Capitan.

For the first time, I imported a directory that contains mp3 files.

But it doesn't appear on playlist(all songs).

And But it does work on Eclipse.

**Comment by octaviospain** [comment]
Can you search the 'Musicott-tracks.json' file in the 'Musicott' folder? By default is located at '~/Music/'. Check if that json file has information about any imported tracks.

Also, try to run and reproduce the import of the directory and after that, search for the file 'Musicott-main-log.txt' at the application folder, lets see which log information could help us.

**Comment by olgierd-on-fire** [comment]
Below is logs when I imported mp3 directory.

Musicott-tracks.json:

```json
{
  "@type":"com.sun.javafx.collections.ObservableMapWrapper"
}
```

Musicott-main-log.txt:

```
com.transgressoft.musicott.MusicottApplication loadConfigProperties 23/09/16 00:21:02 :911000000
0	WARNING:Error loading configuration properties

java.io.FileNotFoundException: resources/config/config.properties (No such file or directory)
java.io.FileInputStream.open0(Native Method)
java.io.FileInputStream.open(FileInputStream.java:195)
java.io.FileInputStream.<init>(FileInputStream.java:138)
java.io.FileInputStream.<init>(FileInputStream.java:93)
com.transgressoft.musicott.MusicottApplication.loadConfigProperties(MusicottApplication.java:179)
com.transgressoft.musicott.MusicottApplication.init(MusicottApplication.java:156)
com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:841)
com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
java.lang.Thread.run(Thread.java:745)
javafx.css calculateValue 23/09/16 00:21:03 :371000000
1	WARNING:Caught 'java.lang.ClassCastException: java.lang.String cannot be cast to javafx.scene.paint.Color' while converting value for '-fx-background-color' from rule '*.progress-bar>*.track' in stylesheet jar:file:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss

com.transgressoft.musicott.MusicottApplication lambda$start$0 23/09/16 00:22:45 :628000000
2	INFO:Exiting Musicott
```

**Comment by octaviospain** [comment]
I just introduced some log messages in the code. Please pull the latest version, and add the following line in `resources/config/config.properties`:
```
com.transgressoft.musicott.tasks.level=ALL
```
Try to import files again. Please check if the mp3 extension is selected in preferences like  explained in [this wiki page](https://github.com/octaviospain/Musicott/wiki/Importing-files), and copy & paste again the log messages here if the problem persists.

**Comment by olgierd-on-fire** [comment]
@octaviospain It's weird. Suddenly It's working. Nothing log messages.

**Comment by octaviospain** [comment]
Good then.
