### ISSUE TITLE
I want to know why you used Sun's FX module?

### ISSUE THREAD

**Issue by olgierd-on-fire** [octaviospain/Musicott#4]
I'm reading your source code. I found there is Sun's FX module in MusicottApplication.java

```java
public static void main(String[] args) {
    initializeLogger();
    LauncherImpl.launchApplication(MusicottApplication.class, MainPreloader.class, args);
}
```

and

```java
@Override
public void init() throws Exception {
	if (preferences.getMusicottUserFolder() == null || ! new File(preferences.getMusicottUserFolder()).exists()) {
			LauncherImpl.notifyPreloader(this, new CustomProgressNotification(0, FIRST_USE_EVENT));
    }
```

Did you find other solutions without Sun's FX modules?

**Comment by octaviospain** [comment]
I didn't find other packages I could use instead of Sun's packages :/ And my IDE only suggests those modules, and if they work, why change?

**Comment by olgierd-on-fire** [comment]
@octaviospain You're right. I just want to know there are other solutions without JavaFX 2 modules but FX 8.
