### ISSUE TITLE
com.worldsworstsoftware unable to find

### ISSUE THREAD

**Issue by cmlanche** [octaviospain/Musicott#8]
<dependency>
            <groupId>com.worldsworstsoftware</groupId>
            <artifactId>itunesutilities</artifactId>
            <version>1.2</version>
            <scope>compile</scope>
        </dependency>

this dependency unable to be download

**Comment by octaviospain** [comment]
I forgot to include the mvn:install command before executing the run maven command. Readme is now updated, you have to run at the project root:
```
mvn install:install-file -Dfile=lib/TarsosTranscoder-1.2.jar -DgroupId=be.tarsos -DartifactId=transcoder -Dversion=1.2 -Dpackaging=jar
mvn install:install-file -Dfile=lib/iTunesUtilities.jar -DgroupId=com.worldsworstsoftware -DartifactId=itunesutilities -Dversion=1.2 -Dpackaging=jar
mvn install:install-file -Dfile=lib/jaudiotagger-2.2.6-SNAPSHOT.jar -DgroupId=net.jthink -DartifactId=jaudiotagger -Dversion=2.2.6-SNAPSHOT -Dpackaging=jar
```
and then
```
mvn exec:java -Dexec.mainClass=com.transgressoft.musicott.MusicottApplication
```
